const CartActionTypes = {
    TOGGLE_CLASS_HIDDEN: "TOGGLE_CLASS_HIDDEN",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART"
}

export default CartActionTypes;